### ISSUE TITLE
Rebuild All не собирает модули

### ISSUE THREAD

**Issue by serssp** [consulo/consulo-dotnet#56]
Возможно из-за возвращения пустого массива в  DotNetCompiler.getInputFileTypes ?

**Comment by VISTALL** [comment]
Тоисть в .NET проекте - Rebuild All не собирает все модули?

**Comment by serssp** [comment]
Создал визардом .Net проект, один модуль.  
"Make module" сборку собирает, dll я получаю. Если нажать "Rebuild All" в каталог попадают только зависимые dll собственно компиляция не выполняется.
Я немного потрейсил :)
Rebuild All вызывает CompileDriver#translate, далее по каждому модулю, перебераются трансляторы. 
А в if где формируется список файлов для компиляции мы не заходим. Т.к. DotNet компилятор не первый, а условие не выполняется.
```
if (snapshot == null || ContainerUtil.intersects(generatedTypes, compilerManager.getRegisteredInputTypes(compiler)))
```
compilerManager.getRegisteredInputTypes вызвращает пустой массив, т.к. компилятор не регистрирует расширения файлов.
Как то так...

**Comment by VISTALL** [comment]
Спасибо. Я помню этот код. Что бы вернуть там нужно, что бы в текущем контексте(плагин .NET) ничего не известно про C# плагин и про другие. Я точно не помню логику, но если Вы точно сказали, значит нужно будет править платформу (или убрать с .NET плагин компилятор для языков)

**Comment by VISTALL** [comment]
Обновил коммент, неверно написал

**Comment by VISTALL** [comment]
Но как оказалось это не так. Исправилено в https://github.com/consulo/consulo/commit/be83cb7b2c43ab3d15364b52c45ab312a818a36a

Если интересно могу обьяснить в чем была проблема

**Comment by serssp** [comment]
Конечно интересно.

**Comment by VISTALL** [comment]
По сути банальная проблема. Я не досмотрел. 

Есть интерфейс CompileModuleScopeFactory, который создает Scope для модуля во время компиляции. 

По дефолту - создается ModuleCompileScope, и он ищет в Sources папках(как в java src/ и прочее).

Как известно вам в .NET - нету подобного, все ищется в корневой.

Make Module - правильно создавал Scope для компиляции. А вот Rebuild создавал класс по имени ProjectScope. В нем и была проблема. По сути он - Composite Scope of All Modules, но он обходил CompileModuleScopeFactory.  В итоге они искал в папках которые помечены как Sources, а таких небыло в проекте.
