### ISSUE TITLE
Debugger same field shown twice (once empty once with correct value)

### ISSUE THREAD

**Issue by winalex** [consulo/consulo-dotnet#73]
<img width="1386" alt="screen shot 2016-05-10 at 1 34 51 pm" src="https://cloud.githubusercontent.com/assets/689092/15145280/f34b0de2-16b4-11e6-9fec-709823f14b7c.png">

**Comment by VISTALL** [comment]
I found a problem. Another Attributes - is a abstract property. I will skip it

**Comment by winalex** [comment]
LIKE

**Comment by VISTALL** [comment]
Fixed. Thanks
