### ISSUE TITLE
Event log - default message 

### ISSUE THREAD

**Issue by cupsster** [consulo/consulo-dotnet#77]
Hi there I can't clear default message that pops up every time I start up Consulo.
It is this message:
5:44:02 PM .NET Debugging API
           Plugin .NET debugging API was greatly changed. 
           It required action for implementing another .NET debuggers. 
           What why you can found some new bugs in already exists functional.
           Please report it here.
           Unity plugin now required Mono plugin, please install if you don't have it.
           Introduced initial implementation for Microsoft .NET debugger and Exception Breakpoints. 
           I apologize for the inconvenience, VISTALL (show balloon)

Every time I right click and select clear, next time I start it it is there again :)

**Comment by VISTALL** [comment]
HI. This message will be removed after one month after change. (1 june 2016)
