### ISSUE TITLE
C# doesn't highlight some operators

### ISSUE THREAD

**Issue by Zoodinger** [consulo/consulo-dotnet#78]
Syntax highlighting doesn't work for some operators. It doesn't work for at least &&, || and most operators containing = (like +=, |=, etc) with the exception of ==, <=, >=.

This issue exists in build #1356

Edit: My apologies, I meant to add this to consulo-csharp

**Comment by VISTALL** [comment]
You changed color of operators in **Colors & Fonts** and it has no effects ?
