### ISSUE TITLE
Support of more than 2 classes in one file

### ISSUE THREAD

**Issue by pizzaeater** [consulo/consulo-dotnet#80]
Now if I create two classes or a class and a struct in a single file, Conuslo doesn't resolve these classes and structs. I need to change all these cases in my existing project to fix the issue. It makes Consulo useless for existing projects.

**Comment by VISTALL** [comment]
Can you provide example ? I think you found a bug or do something  wrong.

**Comment by pizzaeater** [comment]
Here we go:

**File LabyrinthTileData.cs:**

```
public struct LabyrinthTileBorderBits {
	public const uint Right = 0x1;
	public const uint Bottom = 0x2;
}

public class LabyrinthTileData {
	public uint zoneIndex;
	public uint bordersMask;

	public LabyrinthTileData Clone() {
		LabyrinthTileData tileData = new LabyrinthTileData ();
		tileData.zoneIndex = zoneIndex;
		tileData.bordersMask = this.bordersMask;

		return tileData;
	}
}
```

<img width="433" alt="screen shot 2016-09-14 at 16 32 21" src="https://cloud.githubusercontent.com/assets/2511553/18516372/f5113b04-7a98-11e6-99cd-0ef12a44f746.png">

**Comment by pizzaeater** [comment]
In classic Intellij Idea (with other languages) it works.

**Comment by VISTALL** [comment]
>> In classic Intellij Idea (with other languages) it works.

There no IJ implementation inside C# (own language own implementation)

Need some time for test

**Comment by VISTALL** [comment]
![](http://klikr.org/8d9135e92343db966da9c289a28d.png)

There no problem.

How you create file? (and project)

**Comment by VISTALL** [comment]
I think you created file via Unity Editor. You need call 'Re-import Project' (right click on project dir)

**Comment by pizzaeater** [comment]
Yes, you are right, it's created in MonoDevelop. Thank you very much for quick help!

**Comment by VISTALL** [comment]
Ok
