### ISSUE TITLE
Consulo mark lambdas returning a delegate as not resolved

### ISSUE THREAD

**Issue by rogeratplumbee** [consulo/consulo-dotnet#82]
I have this code that compiles and it's valid:

```
        public delegate void MyDelegateType();

        public void Test(){

            MyFunction<MyDelegateType>(() => this.MethodThatMatchDelegateSignature);
        }

        public void MethodThatMatchDelegateSignature(){
            //Do more things
        }

        public void MyFunction<TMyDelegateType>(Func<TMyDelegateType> method)
        {
            //Do Things
        }

```

and the IDE say this:
<img width="328" alt="screen shot 2016-10-18 at 12 18 23" src="https://cloud.githubusercontent.com/assets/5928367/19475642/1d9c8584-952d-11e6-9d1e-d535e06ab3d8.png">

**Comment by VISTALL** [comment]
Hi. Currently i am busy with next version of Consulo. Sorry.

And next time - please use this repo https://github.com/consulo/consulo-csharp (for C# problems)

Thanks

**Comment by VISTALL** [comment]
moved to C# repository https://github.com/consulo/consulo-csharp/issues/461

**Comment by VISTALL** [comment]
fixed
