### ISSUE TITLE
Error on Console.ReadKey

### ISSUE THREAD

**Issue by YT-GameWorks** [consulo/consulo-dotnet#87]
I am currently making a server for unity multiplayer in C# and .NET, and when I try:
```
using System;

namespace GameServer
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.Title = "Game Server";
            Console.WriteLine(" ");
            Server.Start(50, 26950);

            Console.ReadKey();
        }
    }
}
```
It kicks out this error at "Console.ReadKey"

> Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
>    at System.Console.ReadKey(Boolean intercept)
>    at GameServer.Program.Main(String[] args) in D:\unity projects\Game Server\Program.cs:line 13

Server.Start(); is a function in another class 😄. Hope this helps you amazing devs fix this issue (yes, I don't know how to end this lol)

**Comment by VISTALL** [comment]
Hello again. Can you say your env? and project setup. MS/Mono, project model

**Comment by YT-GameWorks** [comment]
hello, I am using .NET v4.7.1 and standard Console application setup and consulo version: 2020.9. also complete sidenote: do you guys have a discord server? where we could communicate more effectively?

**Comment by VISTALL** [comment]
Oh. it's mean you using MSBuild (vs projects). It's painful will be. 

My community is too small for discord :) I'm always answer via email, or gh, or discuss. Anyway - i'm using discord for other reasons:)

**Comment by YT-GameWorks** [comment]
Yea, you ae one of the most active developers ( of ides ) that I've seen yet! I have convinced many of my friends to use consulo and they love it! I also promote it in my youtube channel :)one day this will be a big IDE ! I remember I saw this project a year or two ago, and I dismissed it thinking it would die.. I was so wrong !! hope this ide grows! Also if you are making a server for this, when you have a bigger community, hit me up if you need discord bots ( I make them :) )!

**Comment by VISTALL** [comment]
> Yea, you are one of the most active developers ( of ides ) that I've seen yet!
Maybe. 

Consulo is my primary IDE. I want create alternative for IDEA, MonoDevelop (remember first it's was unity ide). And now i can't use IDEA or VS :D

**Comment by VISTALL** [comment]
Note for me. Use PtyCommandLine

Note for others. At current moment I'm  working on migration to new runtime, all plugin issues delayed

**Comment by YT-GameWorks** [comment]
> Note for me. Use PtyCommandLine
> 
> Note for others. At current moment I'm working on migration to new runtime, all plugin issues delayed

Yay! Good luck!

**Comment by VISTALL** [comment]
Hello. There two news. 

Good. I pushed test change for support different console modes:

![](https://klikr.org/93e553dc83801a1196d336af8834.png)

I think later need create some documentation how it works (for example builtin sometimes more simple, but in some cases not work as expected, emulation - as is, external  - running external terminal without ide one)

And bad news. Consulo have straightforward developing. There no backports, etc. Current changes area inside **nightly** channel (https://github.com/consulo/EntryPoint/blob/master/Update%20Channels.md) with Consulo **nightly** 

Iteration to release branch delayed(around month), due I'm not sure in current stability. I'm always sit at **nightly**  branch. 

You decide what you will do:)

**Comment by YT-GameWorks** [comment]
> Hello. There two news.
> 
> Good. I pushed test change for support different console modes:
> 
> ![](https://camo.githubusercontent.com/0c6a53d358f09b3fda70c1fd672fc7c67c4702ff/68747470733a2f2f6b6c696b722e6f72672f393365353533646338333830316131313936643333366166383833342e706e67)
> 
> I think later need create some documentation how it works (for example builtin sometimes more simple, but in some cases not work as expected, emulation - as is, external - running external terminal without ide one)
> 
> And bad news. Consulo have straightforward developing. There no backports, etc. Current changes area inside **nightly** channel (https://github.com/consulo/EntryPoint/blob/master/Update%20Channels.md) with Consulo **nightly**
> 
> Iteration to release branch delayed(around month), due I'm not sure in current stability. I'm always sit at **nightly** branch.
> 
> You decide what you will do:)

Thanks :) I'am always on nightly 😄
